# Generated by Django 4.2.5 on 2023-09-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTagEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tagentity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.taskentity')),
            ],
        ),
        migrations.AddField(
            model_name='tagentity',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tags', through='todo.TaskTagEntity', to='todo.taskentity'),
        ),
    ]
